void identificadorGet(int isCalculusContext);
void identificadorSet(void);
void closeP(void);
void mainRes(void);
void linebreak(void);
void end(void);
void whitespace(void);
void doubleDotRes(void);
void tipoInt(void);
void tipoFloat(void);
void tipoString(void);
void tipoBool(void);
void equalSignRes(void);
void quotesRes(void);
void comparisonOp(void);
void openP(void);
void ignoreSpace(void);
void ignoreLinebreak(void);
void ignoreTabs(void);
void myFloat(int type);
void myInt(int type);
void number(int definition, int isFloat);
void myString(int definition);
void myBool(int definition);
void value(int definition, int isFloat);
void NegFac(int definition, int isFloat);
void Parenteses(int definition, int isFloat);
void Pot(int definition, int isFloat);
void MultDiv(int definition, int isFloat);
void somaSub(int definition, int isFloat);
void calculo(int definition, int isFloat);
void begin(void);
void attrInt(void);
void attrFloat(void);
void attrString(void);
void attrBool(void);
void tipagemVar(void);
void atribuicao(void);
void variavel(void);
void printing(void);
void printParameters(void);
void myPrint(void);
void input(void);
void dado(void);
void condicao(void);
void elseStatement(void);
void ifStatement(void);
void whileStatement(void);
void programa(void);
void runParser(char program[], int isDebugOn);
